title: Harald Vohringer
email: harald.voeh@gmail.com
description: Personal website
author: Harald Vohringer
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "http://sagar87.github.io"  # Sitemap base URL.
markdown: kramdown
kramdown:
    math_engine: katex
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed

#   - jekyll-katex
# katex:
#   js_path: "assets"  # Path used to search for katex.min.js
#   rendering_options:
#     # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
#     throw_error: false      # throwOnError - set to false if you want rendering to output error as text rather than a build error
#     error_color: "#cc0000"  # errorColor